# Change these first
owner: sweetvinyl # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Sugarserver
    url: https://sugarserver.sweetvinyl.com/uptimerobotcheck

status-website:
  publish: true
  theme: night
  apiBaseUrl: https://api.github.com
  cname: status.sweetvinyl.com
  #baseUrl: /uptime
  logoUrl: https://sweetvinyl.com/cdn/shop/files/SweetVinyl_logo_on_white_160x120_b8e6a15b-91a1-4203-baed-5f07b2271c97_410x.png?v=1613681389
  name: Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page for SweetVinyl
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
